# document and style R code using a reusable workflow
name: call-doc-and-style-r
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    paths:
      - 'R/**'
      - 'tests/**'
      - 'vignettes/**'
    branches: [main]
  pull_request:
    paths:
      - 'R/**'
      - 'tests/**'
      - 'vignettes/**'
jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/doc-and-style-r.yml@main
    with:
      use-air: true
      run-rm_dollar_sign: true
      commit-directly: true